//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oswam2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid OrderID { get; set; }
        public string ProductID { get; set; }
        public string OrderStatus { get; set; }
    }
}
