//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oswam2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.LocalInventories = new HashSet<LocalInventory>();
        }
    
        public string ID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> DimLength { get; set; }
        public Nullable<decimal> DimWidth { get; set; }
        public Nullable<decimal> DimHeight { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public int NumPlaced { get; set; }
        public Nullable<int> NumReserved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalInventory> LocalInventories { get; set; }
    }
}
