//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oswam2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shelf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shelf()
        {
            this.LocalInventories = new HashSet<LocalInventory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LocationX { get; set; }
        public Nullable<int> LocationY { get; set; }
        public decimal maxCapacity { get; set; }
        public Nullable<decimal> currentCapacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalInventory> LocalInventories { get; set; }
    }
}
