//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oswam2015.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shelf
    {
        public int ID { get; set; }
        public int LocationX { get; set; }
        public int LocationY { get; set; }
        public Nullable<decimal> availableVolume { get; set; }
        public Nullable<decimal> availableWeight { get; set; }
        public bool CellType { get; set; }
        public bool ContainsItems { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeomPoint { get; set; }
        public Nullable<int> PackDistance { get; set; }
    }
}
